// packages/reporter-solid/src/ValidationMessage.tsx
import type { Errors, Obj } from '@felte/common';
import type { JSX } from 'solid-js';
import { _get, getPath, createId } from '@felte/common';
import {
  onMount,
  createSignal,
  Show,
  createEffect,
  onCleanup,
  mergeProps,
} from 'solid-js';
import { errorStores, warningStores } from './stores';

export type ValidationMessageProps = {
  for: string;
  level?: 'error' | 'warning';
  children: (messages: string | string[] | undefined) => JSX.Element;
};

export function ValidationMessage<Data extends Obj = Obj>(
  props: ValidationMessageProps
) {
  props = mergeProps({ level: 'error' }, props);
  const [errorPath, setErrorPath] = createSignal<string>();
  const [errors, setErrors] = createSignal<Errors<Data> | Record<string, any>>(
    {}
  );
  const [messages, setMessages] = createSignal<string | string[]>();
  function getFormElement(element: HTMLDivElement) {
    return element.closest('form');
  }

  const id = createId(21);
  let unsubscribe: (() => void) | undefined;
  onMount(() => {
    const element = document.getElementById(id) as HTMLDivElement;
    const path = props.for;
    setErrorPath(getPath(element, path));
    const formElement = getFormElement(element) as HTMLFormElement;
    const reporterId = formElement?.dataset.felteReporterSolidId;
    if (!reporterId) return;
    if (props.level === 'error') {
      const errors = errorStores[reporterId];
      unsubscribe = errors.subscribe(($errors) => setErrors(() => $errors));
    } else {
      const warnings = warningStores[reporterId];
      unsubscribe = warnings.subscribe(($warnings) =>
        setErrors(() => $warnings)
      );
    }
  });

  onCleanup(() => unsubscribe?.());

  createEffect(() => {
    const path = errorPath();
    if (path) setMessages(_get(errors(), path) as any);
  });

  return (
    <>
      <div id={id} style="display: none;" />
      <Show when={errorPath()}>{props.children(messages())}</Show>
    </>
  );
}

// packages/reporter-preact/src/ValidationMessage.tsx
import type { VNode, ComponentType } from 'preact';
import { h, Fragment } from 'preact';
import { useState, useEffect, useMemo } from 'preact/hooks';
import { _get, getPath, createId } from '@felte/common';
import { errorStores, warningStores } from './stores';

export type ValidationMessageProps = {
  [key: string]: any;
  for: string;
  level?: 'error' | 'warning';
  children: (
    messages: string[] | null
  ) => VNode<any> | undefined | null | Element | Element[] | VNode<any>[];
  as?: string | ComponentType<any>;
};

export function ValidationMessage(props: ValidationMessageProps) {
  const { level: _level, for: path, children, as, id: _id, ...rest } = props;
  const level = props.level ?? 'error';
  const [messages, setMessages] = useState<string[] | null>(null);
  const id = useMemo(() => props.id ?? createId(21), []);
  function getFormElement(element: HTMLDivElement) {
    return element.closest('form');
  }

  useEffect(() => {
    let unsubscriber;
    // To guarantee the DOM has rendered we need to setTimeout
    setTimeout(() => {
      const element = document.getElementById(id) as HTMLDivElement;
      const errorPath = getPath(element, path);
      const formElement = getFormElement(element) as HTMLFormElement;
      const reporterId = formElement?.dataset.felteReporterPreactId;
      if (!reporterId) return;
      if (level === 'error') {
        const errors = errorStores[reporterId];
        unsubscriber = errors.subscribe(($errors) => {
          setMessages(_get($errors, errorPath) as any);
        });
      } else {
        const warnings = warningStores[reporterId];
        unsubscriber = warnings.subscribe(($warnings) => {
          setMessages(_get($warnings, errorPath) as any);
        });
      }
    });
    return unsubscriber;
  }, []);

  if (!as) {
    return (
      <>
        <div id={id} style={{ display: 'none' }} />
        {children(messages)}
      </>
    );
  }
  return h(as as any, { ...rest, id }, children(messages));
}
