// packages/reporter-solid/src/ValidationMessage.tsx
import type { Errors, Obj } from '@felte/common';
import type { JSX } from 'solid-js';
import { _get, getPath } from '@felte/common';
import {
  onMount,
  createSignal,
  Show,
  createEffect,
  onCleanup,
  mergeProps,
} from 'solid-js';
import { errorStores, warningStores } from './stores';
import { createId } from './utils';

export type ValidationMessageProps = {
  for: string;
  index?: string | number;
  level?: 'error' | 'warning';
  children: (messages: string | string[] | undefined) => JSX.Element;
};

export function ValidationMessage<Data extends Obj = Obj>(
  props: ValidationMessageProps
) {
  props = mergeProps({ level: 'error' }, props);
  const [errorPath, setErrorPath] = createSignal<string>();
  const [errors, setErrors] = createSignal<Errors<Data>>({});
  const [messages, setMessages] = createSignal<string | string[]>();
  function getFormElement(element: HTMLDivElement) {
    let form = element.parentNode;
    if (!form) return;
    while (form && form.nodeName !== 'FORM') {
      form = form.parentNode;
    }
    return form;
  }

  const id = createId(21);
  let unsubscribe: (() => void) | undefined;
  onMount(() => {
    const element = document.getElementById(id) as HTMLDivElement;
    const path =
      typeof props.index !== 'undefined'
        ? `${props.for}[${props.index}]`
        : props.for;
    setErrorPath(getPath(element, path));
    const formElement = getFormElement(element) as HTMLFormElement;
    const reporterId = formElement?.dataset.felteReporterSolidId;
    if (!reporterId) return;
    if (props.level === 'error') {
      const errors = errorStores[reporterId];
      unsubscribe = errors.subscribe(($errors: Errors<Data>) =>
        setErrors(() => $errors)
      );
    } else {
      const warnings = warningStores[reporterId];
      unsubscribe = warnings.subscribe(($warnings: Errors<Data>) =>
        setErrors(() => $warnings)
      );
    }
  });

  onCleanup(() => unsubscribe?.());

  createEffect(() => {
    const path = errorPath();
    if (path) setMessages(_get(errors(), path) as any);
  });

  return (
    <>
      <div id={id} style="display: none;" />
      <Show when={errorPath()}>{props.children(messages())}</Show>
    </>
  );
}

// packages/reporter-react/src/ValidationMessage.tsx
import type { Errors, Obj } from '@felte/common';
import type { ReactNode } from 'react';
import React, { useState, useEffect } from 'react';
import { _get, getPath } from '@felte/common';
import { errorStores, warningStores } from './stores';
import { createId } from './utils';

export type ValidationMessageProps = {
  for: string;
  index?: string | number;
  level?: 'error' | 'warning';
  children: (messages: string | string[] | undefined) => ReactNode;
};

export function ValidationMessage<Data extends Obj = Obj>(
  props: ValidationMessageProps
) {
  const level = props.level ?? 'error';
  const [messages, setMessages] = useState<string | string[]>();
  function getFormElement(element: HTMLDivElement) {
    let form = element.parentNode;
    while (form && form.nodeName !== 'FORM') {
      form = form.parentNode;
    }
    return form;
  }

  const id = createId(21);
  useEffect(() => {
    const element = document.getElementById(id) as HTMLDivElement;
    const path =
      typeof props.index !== 'undefined'
        ? `${props.for}[${props.index}]`
        : props.for;
    const errorPath = getPath(element, path);
    const formElement = getFormElement(element) as HTMLFormElement;
    const reporterId = formElement?.dataset.felteReporterReactId;
    if (!reporterId) return;
    if (level === 'error') {
      const errors = errorStores[reporterId];
      return errors.subscribe(($errors: Errors<Data>) => {
        setMessages(_get($errors, errorPath) as any);
      });
    } else {
      const warnings = warningStores[reporterId];
      return warnings.subscribe(($warnings: Errors<Data>) => {
        setMessages(_get($warnings, errorPath) as any);
      });
    }
  }, []);

  return (
    <>
      <div id={id} style={{ display: 'none' }} />
      {props.children(messages)}
    </>
  );
}
